### ISSUE TITLE
Website hosting etc.

### ISSUE THREAD

**Issue by zockerei** [zockerei/secret-santa#11]

**Comment by zockerei** [comment]
Done with docker-compose and nginx proxy manager

**Comment by zockerei** [comment]
```yaml
services:
  app:
    image: python:3.12-slim
    container_name: secret_santa
    working_dir: /app
    volumes:
      - /mnt/user/appdata/secret-santa:/app
    ports:
      - "5050:5050"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    build:
      context: /mnt/user/appdata/secret-santa
      dockerfile: Dockerfile
    networks:
      - br0

networks:
  br0:
    external: true
```
Hosted on Unraid, duckdns and ssl certificate
